### ISSUE TITLE
Minor Correction on Blog

### ISSUE THREAD

**Issue by lower-case** [aron-bordin/Slide-and-Survive#1]
There's a minor mistake on the first line of Part IV-Game Scene of your blog,it says that app.js file is in res folder but it should be in src folder.
Also in the same part the code snippet has an extra ending curly brace on line 24.
BTW Nice Post Thanks for it.

**Comment by nrbrd** [comment]
Fixed, thanks. I don't know if you would like it, but I'll be posting a game based on Space Invader, probably in the next week.
